<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart Testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1f482da4-45ba-42e1-a0ce-3ea8069a3ddd</testSuiteGuid>
   <testCaseLink>
      <guid>d3967e63-8c16-4423-9d1d-0345d72d9ccc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC01 - User can access cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6fa4d728-8c85-463c-bc65-a22895e9115f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC02 - User can see product have been added to the cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2145b6ad-654c-4e7d-8167-4aeae4d20905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50d4cbdc-6d0e-4aff-9ad6-25646ee04fb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3451b318-03ad-4621-a26a-6399f1e01e29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7af77d75-d978-44e3-a07d-bd61c079ee63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC03 - User can delete product form cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>719745c7-8dc0-4b74-9e7e-b56f9c7ddd59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12651236-2fa0-4c8a-92d6-07d048d6b007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebdaa849-6fb0-4b5c-9c77-15be64cbd5a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c5e5b4b-8b6e-4861-8567-7ebe76055d76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC04 - User can click place order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d59bbd5-0ec1-4817-aba0-79865862eb11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74a808e-69a6-4501-8da2-e0710ab67d28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>130ca337-4dde-414c-badd-c25690e29da2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7948ee8-5bb0-4e96-b097-8a2b054a2ab4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC05 - User can close place order form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2bfd6f-c54b-4acc-b9c3-2108557f145d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4d48135-84bb-4a37-ab3c-05d879d3c642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b5dfb3-870b-46dd-b5f3-17fbb7ed078c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2e0987d-a812-4bdc-86ab-42efb48ef257</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC06 - User successful purchase order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fb44d8-afe7-4b66-b658-4f897a8e96c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1e9fa9-404e-4ef1-9042-b3d31b1c7d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284a2ceb-01c8-4c43-89f9-13f5a6426f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496545db-5366-4b26-aa02-158732b8ed1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171a80f4-5612-4b8e-817e-9adf5a1cf538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3518a328-58c7-4a0e-ad26-c234526f59cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caebc2b7-f706-4c38-9b9f-51bc8b20c92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39267365-dfa4-4a24-a4db-31ec2f5bc0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7853425-9e3c-452f-bcae-aaa9dfd1e01c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba7ee563-c140-44f1-b3fc-15eeb23914be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC07 - User can not purchase order when name and credit card empty</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fb44d8-afe7-4b66-b658-4f897a8e96c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1e9fa9-404e-4ef1-9042-b3d31b1c7d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284a2ceb-01c8-4c43-89f9-13f5a6426f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496545db-5366-4b26-aa02-158732b8ed1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171a80f4-5612-4b8e-817e-9adf5a1cf538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3518a328-58c7-4a0e-ad26-c234526f59cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caebc2b7-f706-4c38-9b9f-51bc8b20c92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39267365-dfa4-4a24-a4db-31ec2f5bc0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7853425-9e3c-452f-bcae-aaa9dfd1e01c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
