<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart Testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1f482da4-45ba-42e1-a0ce-3ea8069a3ddd</testSuiteGuid>
   <testCaseLink>
      <guid>b3cf6184-66c6-4a26-a8c5-688b0b502495</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC01 - User can access cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5bec12c4-84c4-41be-9d9b-d80f884a9e2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC02 - User can see product have been added to the cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2145b6ad-654c-4e7d-8167-4aeae4d20905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50d4cbdc-6d0e-4aff-9ad6-25646ee04fb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3451b318-03ad-4621-a26a-6399f1e01e29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8acf5c29-8a57-4caa-ac5e-a8b055e4719b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC03 - User can delete product form cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>719745c7-8dc0-4b74-9e7e-b56f9c7ddd59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12651236-2fa0-4c8a-92d6-07d048d6b007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebdaa849-6fb0-4b5c-9c77-15be64cbd5a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b086e04d-9200-4ed9-a931-c47bdc5bec47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC04 - User can click place order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d59bbd5-0ec1-4817-aba0-79865862eb11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74a808e-69a6-4501-8da2-e0710ab67d28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>130ca337-4dde-414c-badd-c25690e29da2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>954e88a2-8afa-4d90-8f85-33f0c7befe90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC05 - User can close place order form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2bfd6f-c54b-4acc-b9c3-2108557f145d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4d48135-84bb-4a37-ab3c-05d879d3c642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b5dfb3-870b-46dd-b5f3-17fbb7ed078c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0688e396-bfbe-43a0-a03c-df7b6117f508</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC06 - User successful purchase order without log in</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fb44d8-afe7-4b66-b658-4f897a8e96c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1e9fa9-404e-4ef1-9042-b3d31b1c7d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284a2ceb-01c8-4c43-89f9-13f5a6426f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496545db-5366-4b26-aa02-158732b8ed1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171a80f4-5612-4b8e-817e-9adf5a1cf538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3518a328-58c7-4a0e-ad26-c234526f59cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caebc2b7-f706-4c38-9b9f-51bc8b20c92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39267365-dfa4-4a24-a4db-31ec2f5bc0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7853425-9e3c-452f-bcae-aaa9dfd1e01c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93ea2caf-0c5d-49ba-9858-51c3ffcb08ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC07 - User successful purchase order with log in</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2abe6731-d229-4bf1-9368-31a23ec5b311</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c5825e-32d2-4799-9518-b8d723e957e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fb44d8-afe7-4b66-b658-4f897a8e96c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1e9fa9-404e-4ef1-9042-b3d31b1c7d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284a2ceb-01c8-4c43-89f9-13f5a6426f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496545db-5366-4b26-aa02-158732b8ed1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171a80f4-5612-4b8e-817e-9adf5a1cf538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3518a328-58c7-4a0e-ad26-c234526f59cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caebc2b7-f706-4c38-9b9f-51bc8b20c92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39267365-dfa4-4a24-a4db-31ec2f5bc0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7853425-9e3c-452f-bcae-aaa9dfd1e01c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5914d74e-86f6-4d3a-a5b6-71ceb24977db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC08 - User can not purchase order when name and credit card empty</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07fb44d8-afe7-4b66-b658-4f897a8e96c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1e9fa9-404e-4ef1-9042-b3d31b1c7d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284a2ceb-01c8-4c43-89f9-13f5a6426f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496545db-5366-4b26-aa02-158732b8ed1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171a80f4-5612-4b8e-817e-9adf5a1cf538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3518a328-58c7-4a0e-ad26-c234526f59cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caebc2b7-f706-4c38-9b9f-51bc8b20c92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39267365-dfa4-4a24-a4db-31ec2f5bc0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7853425-9e3c-452f-bcae-aaa9dfd1e01c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
