<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelLogIn</name>
   <tag></tag>
   <elementGuidId>40939231-b8cc-4c9e-b872-a890af6ed27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='logInModal']//div[@class='modal-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='logInModal']//div[@class='modal-header']</value>
   </webElementProperties>
</WebElementEntity>
