<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelPlaceOrderForm</name>
   <tag></tag>
   <elementGuidId>c8428df4-473c-4f73-aae1-06e6fc1ec2a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='orderModal']//div[@class='modal-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='orderModal']//div[@class='modal-header']</value>
   </webElementProperties>
</WebElementEntity>
