<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelNewMessage</name>
   <tag></tag>
   <elementGuidId>f2377496-9ec4-4682-a4b9-d5d47c0f0507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='exampleModal']//div[@class='modal-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']//div[@class='modal-header']</value>
   </webElementProperties>
</WebElementEntity>
