<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chooseProductPrice</name>
   <tag></tag>
   <elementGuidId>1852e688-bbd7-4ef8-b7af-68e4ecea574b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[a[text()='${productName}']]/following-sibling::h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[a[text()='${productName}']]/following-sibling::h5</value>
   </webElementProperties>
</WebElementEntity>
