<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelSignUp</name>
   <tag></tag>
   <elementGuidId>f4ec720d-fbd4-4061-8cd3-a16354726033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='signInModal']//div[@class='modal-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='signInModal']//div[@class='modal-header']</value>
   </webElementProperties>
</WebElementEntity>
